# Configuration for Black.

[tool.black]
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | tests
  | vendor
)/
'''

[tool.pip-tools]
generate-hashes = true
output-file = "requirements-dev.txt"
