name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v10.0.1

    - name: Checkout the latest code
      uses: actions/checkout@v7

    - name: Check formatting
      run: uv run ruff check .
